spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/rgr/protocol/openid-connect/certs}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

user.service.url=${USER_SERVICE_URL:http://localhost:8084}
restaurant.service.url=${RESTAURANT_SERVICE_URL:http://localhost:8081}
